[tool.poetry]
name = "stable-diffusion-webui"
version = "0.1.0"
description = ""
authors = ["AUTOMATIC1111"]
readme = "README.md"
packages = [{ include = "stable_diffusion_webui" }]

[tool.poetry.dependencies]
python = "3.10.9"
blendmodes = "^2022"
accelerate = "^0.15.0"
basicsr = "^1.4.2"
fairscale = "0.4.4"
fonts = "^0.0.3"
font-roboto = "^0.0.1"
gfpgan = "^1.3.8"
gradio = "3.16.2"
invisible-watermark = "^0.1.5"
numpy = "^1.24.1"
omegaconf = "^2.3.0"
opencv-contrib-python = "^4.7.0.68"
requests = "^2.28.2"
piexif = "^1.1.3"
pillow = "^9.4.0"
pytorch-lightning = "1.7.7"
realesrgan = "^0.3.0"
scikit-image = ">=0.19"
timm = "0.4.12"
transformers = "4.19.2"
torch = "^1.13.1"
einops = "^0.6.0"
jsonmerge = "^1.9.0"
clean-fid = "^0.1.35"
resize-right = "^0.0.2"
torchdiffeq = "^0.2.3"
kornia = "^0.6.9"
lark = "^1.1.5"
inflection = "^0.5.1"
gitpython = "^3.1.30"
torchsde = "^0.2.5"
safetensors = "^0.2.8"
psutil = "^5.9.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
